### ISSUE TITLE
Trouble running the test file

### ISSUE THREAD

**Issue by jarvislam1999** [kumokay/placethings#1]
Hi, I installed everything as asked but did not manage to run the main code:

Here's the output:
$ python3 main.py demo -tc test_ddflow_demo_local.Test -v

2019-07-24 15:50:48,956 |[INFO] demo: run test case: Test in placethings.demo.test_ddflow_demo_local
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "main.py", line 107, in main
    args.func(args)
  File "main.py", line 87, in demo
    demo_case_module = importlib.import_module(module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/sandlab/placethings/placethings/demo/test_ddflow_demo_local.py", line 9, in <module>
    from placethings.config.helper import ConfigDataHelper
  File "/home/sandlab/placethings/placethings/config/helper.py", line 10, in <module>
    from placethings.graph_gen.wrapper import graph_gen
  File "/home/sandlab/placethings/placethings/graph_gen/wrapper/graph_gen.py", line 7, in <module>
    from placethings.graph_gen import topo_graph, task_graph, device_graph
  File "/home/sandlab/placethings/placethings/graph_gen/topo_graph.py", line 10, in <module>
    from placethings.config import nw_device_data
ImportError: cannot import name 'nw_device_data'

Would anyone be able to help? Here's my folder structure:
$ ls placethings/config/
base  common.py  definition  helper.py  __init__.py  __pycache__  wrapper

$ ls placethings/
config  demo  graph_gen  ilp  __init__.py  netgen  __pycache__  utils

Thank you!

**Comment by kumokay** [comment]
Hi Jarvis, I think I accidentally delete the file during code refactoring. Can you switch to master branch? Thanks.

**Comment by jarvislam1999** [comment]
Did that and the code worked. Thanks! U r awesome.
